# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
notifications:
  email: false
addons:
  apt:
    packages:
    - cmake
    - libxxf86vm-dev
    sources:
    - kubuntu-backports
